### ISSUE TITLE
Cannot build on MacOS

### ISSUE THREAD

**Issue by 616slayer616** [auerswal/ssocr#17]
I can’t get it to build on macOS 12.1.

I installed imlib2  1.7.5. There is only this 1 version from homebrew.

But it seems to be missing 'imlib2-config'?
And I cannot find a package like this.

Do you know anything about this?

Also it would be great if there was a homebrew formula for ssocr.

<details>
  <summary>Log</summary>

```
make: imlib2-config: Command not found
make: imlib2-config: Command not found
cc   ssocr.o imgproc.o help.o charset.o  -lm  -o ssocr
Undefined symbols for architecture x86_64:
  "_imlib_clone_image", referenced from:
      _set_pixels_filter in imgproc.o
      _set_pixels_filter_iter in imgproc.o
      _dilation in imgproc.o
      _erosion in imgproc.o
      _closing in imgproc.o
      _opening in imgproc.o
      _keep_pixels_filter in imgproc.o
      ...
  "_imlib_context_get_image", referenced from:
      _draw_pixel in imgproc.o
      _draw_fg_pixel in imgproc.o
      _draw_bg_pixel in imgproc.o
      _set_pixels_filter in imgproc.o
      _keep_pixels_filter in imgproc.o
      _gray_stretch in imgproc.o
      _dynamic_threshold in imgproc.o
      ...
  "_imlib_context_set_color", referenced from:
      _main in ssocr.o
      _scanline in ssocr.o
      _ssocr_set_color in imgproc.o
      _draw_pixel in imgproc.o
      _draw_fg_pixel in imgproc.o
      _draw_bg_pixel in imgproc.o
      _set_pixels_filter in imgproc.o
      ...
  "_imlib_context_set_image", referenced from:
      _main in ssocr.o
      _scanline in ssocr.o
      _draw_pixel in imgproc.o
      _draw_fg_pixel in imgproc.o
      _draw_bg_pixel in imgproc.o
      _set_pixels_filter in imgproc.o
      _set_pixels_filter_iter in imgproc.o
      ...
  "_imlib_create_cropped_image", referenced from:
      _crop in imgproc.o
  "_imlib_free_image", referenced from:
      _main in ssocr.o
      _set_pixels_filter_iter in imgproc.o
      _dilation in imgproc.o
      _erosion in imgproc.o
      _closing in imgproc.o
      _opening in imgproc.o
  "_imlib_free_image_and_decache", referenced from:
      _main in ssocr.o
  "_imlib_image_draw_line", referenced from:
      _main in ssocr.o
  "_imlib_image_draw_pixel", referenced from:
      _scanline in ssocr.o
      _draw_pixel in imgproc.o
      _draw_fg_pixel in imgproc.o
      _draw_bg_pixel in imgproc.o
      _set_pixels_filter in imgproc.o
      _keep_pixels_filter in imgproc.o
      _gray_stretch in imgproc.o
      ...
  "_imlib_image_draw_rectangle", referenced from:
      _main in ssocr.o
      _keep_pixels_filter in imgproc.o
      _white_border in imgproc.o
  "_imlib_image_get_height", referenced from:
      _main in ssocr.o
      _set_pixels_filter in imgproc.o
      _keep_pixels_filter in imgproc.o
      _gray_stretch in imgproc.o
      _dynamic_threshold in imgproc.o
      _get_threshold in imgproc.o
      _make_mono in imgproc.o
      ...
  "_imlib_image_get_width", referenced from:
      _main in ssocr.o
      _set_pixels_filter in imgproc.o
      _keep_pixels_filter in imgproc.o
      _gray_stretch in imgproc.o
      _dynamic_threshold in imgproc.o
      _get_threshold in imgproc.o
      _make_mono in imgproc.o
      ...
  "_imlib_image_query_pixel", referenced from:
      _main in ssocr.o
      _scanline in ssocr.o
      _set_pixels_filter in imgproc.o
      _keep_pixels_filter in imgproc.o
      _gray_stretch in imgproc.o
      _dynamic_threshold in imgproc.o
      _get_threshold in imgproc.o
      ...
  "_imlib_image_set_format", referenced from:
      _save_image in imgproc.o
  "_imlib_load_image_with_error_return", referenced from:
      _main in ssocr.o
  "_imlib_save_image_with_error_return", referenced from:
      _save_image in imgproc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ssocr] Error 1

```
</details>

**Comment by auerswal** [comment]
Hi,

this seems to be caused by a recent change in Imlib2.

From the ChangeLog:

> v1.7.5 - 2021-12-06
> -------------------
> Kim Woelders (83):
>       […]
>       Drop imlib2-config (use pkg-config)
>       […]

Could you please add the output of the following two commands on your system to this issue?

    pkg-config --cflags imlib2

    pkg-config --libs imlib2

You could try to replace all uses of `imlib2-config` in the `Makefile` with `pkg-config`, e.g., using `sed`, and use that to build `ssocr`:

    mv Makefile Makefile.orig
    sed 's/imlib2-config \(--[^)]*\))/pkg-config \1 imlib2)/' Makefile.orig > Makefile
    make

[The `sed` invocation above should work on macOS, I think.]

On my Ubuntu 18.04 LTS system, `imlib2-config --cflags` and `pkg-config --cflags imlib2` both give an empty line as output, i.e., they give the same output. But the output of `imlib2-config --libs` and `pkg-config --libs imlib2` differ:

    $ imlib2-config --libs
    -L/usr/lib/x86_64-linux-gnu -lImlib2
    $ pkg-config --libs imlib2
    -lImlib2

But replacing `imlib2-config` in the Makefile with `pkg-config` as described above works on Ubuntu 18.04 LTS.

If this works for you, too, I'll probably look into supporting both the older `imlib2-config` and the current `pkg-config` methods transparently in the `Makefile`.

HTH,
Erik

P.S. The Makefile diff is as follows:

```
diff --git a/Makefile b/Makefile
index fbc412b..4c56d9f 100644
--- a/Makefile
+++ b/Makefile
@@ -1,8 +1,8 @@
 # minimal CFLAGS definition (try if compilation fails with default CFLAGS)
-#CFLAGS  := $(shell imlib2-config --cflags)
+#CFLAGS  := $(shell pkg-config --cflags imlib2)
 # default CFLAGS definition
-CFLAGS  := -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all $(shell imlib2-config --cflags) -O3
-LDLIBS  := -lm $(shell imlib2-config --libs)
+CFLAGS  := -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all $(shell pkg-config --cflags imlib2) -O3
+LDLIBS  := -lm $(shell pkg-config --libs imlib2)
 PREFIX  := /usr/local
 BINDIR  := $(PREFIX)/bin
 MANDIR  := $(PREFIX)/share/man/man1
```

**Comment by 616slayer616** [comment]
Wow this is a very detailed answer thank you very much.
It works after applying your diff.

I feel like I should have figured this out myself but I somehow didn't find much info on imlib2 and it’s versions.

**Comment by auerswal** [comment]
I am leaning towards using the following diff for `ssocr`:

```
diff --git a/Makefile b/Makefile
index fbc412b..da11623 100644
--- a/Makefile
+++ b/Makefile
@@ -1,8 +1,8 @@
 # minimal CFLAGS definition (try if compilation fails with default CFLAGS)
-#CFLAGS  := $(shell imlib2-config --cflags)
+#CFLAGS  := $(shell imlib2-config --cflags || pkg-config --cflags imlib2)
 # default CFLAGS definition
-CFLAGS  := -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all $(shell imlib2-config --cflags) -O3
-LDLIBS  := -lm $(shell imlib2-config --libs)
+CFLAGS  := -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all $(shell imlib2-config --cflags || pkg-config --cflags imlib2) -O3
+LDLIBS  := -lm $(shell imlib2-config --libs || pkg-config --libs imlib2)
 PREFIX  := /usr/local
 BINDIR  := $(PREFIX)/bin
 MANDIR  := $(PREFIX)/share/man/man1
```

It would be great if you could test this, too.

TIA,
Erik

**Comment by 616slayer616** [comment]
It works.


It does print the errors though which could be confusing:
<details>
<summary>
Log
</summary

/bin/sh: imlib2-config: command not found
/bin/sh: imlib2-config: command not found
cc -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all -I/usr/local/Cellar/imlib2/1.7.5/include -O3   -c -o ssocr.o ssocr.c
cc -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all -I/usr/local/Cellar/imlib2/1.7.5/include -O3   -c -o imgproc.o imgproc.c
cc -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all -I/usr/local/Cellar/imlib2/1.7.5/include -O3   -c -o help.o help.c
cc -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -fstack-protector-all -I/usr/local/Cellar/imlib2/1.7.5/include -O3   -c -o charset.o charset.c
cc   ssocr.o imgproc.o help.o charset.o  -lm -L/usr/local/Cellar/imlib2/1.7.5/lib -lImlib2 -o ssocr
sed -e 's/@VERSION@/"2.22.0"/' \
            -e "s/@DATE@/2022-01-24/" \
            -e 's/@CRYEARS@/2004-2021/' <ssocr.1.in >ssocr.1

</details>

**Comment by auerswal** [comment]
Thanks!

Yes, the error messages are not nice. I could make this more complicated to detect what is available and use that, or just suppress the error messages.

I'll think about this some more. I just do not know if there are systems with `imlib2-config`, but not `pkg-config` (or without `implib2.pc`) out there, thus I do not want to unconditionally replace `imlib2-config` with `pkg-config`.

Anyway, I intend to commit and push a fix soon, since sooner or later Imlib2 1.7.5 (or later) should reach other package distribution systems which would break the `ssocr` build there, too.

P.S. Regarding a homebrew formula for `ssocr`, I do not use homebrew and thus would not even know if an `ssocr` formula (package?) actually works or not. Somebody else would need to support such a formula (or package). This is the same as with the existing FreeBSD and GNU/Linux distribution `ssocr` packages.

**Comment by 616slayer616** [comment]
Thank you, too!

I will test the fix when you push it.


I will have a look at homebrew formula contribution.
Right now I have no idea what the process is

**Comment by auerswal** [comment]
I have just pushed changes to the `Makefile` that should use `imlib2-config` if available, otherwise `pkg-config`, without generating spurious error messages.

@616slayer616, It would be great if you could test if this works for you with Imlib2 1.7.5 on macOS.

Thanks in advance!

**Comment by 616slayer616** [comment]
Looks good!

Build worked without error messages and my test image is still recognized correctly

**Comment by auerswal** [comment]
Thanks for testing!

**Comment by auerswal** [comment]
I have pushed the tag v2.22.1 for this build fix.
